default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: depot
  password: eim3Vae9fahpheiC9w
  host:     127.0.0.1

development:
  <<: *default
  database: depot

test:
  <<: *default
  database: depot_test

production:
  <<: *default
  database: db/production.sqlite3
